In [7]:
#Write a function to compute 5/0 and use try/except to catch the exceptions.

def div():
    return 5/0

try:
    div()
except ZeroDivisionError as ze:
    print("division by zero!!")
except:
    print("Other exception")

division by zero!!


In [8]:
# Implement a Python program to generate all sentences where subject is in ["Americans",
# "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
# subjects=["Americans ","Indians"]
# verbs=["play","watch"]
# objects=["Baseball","Cricket"]


Subject=['Americans', 'Indians']
Verb=['play', 'watch']
Object=['Baseball', 'Cricket']
All_sentences=[(sub +" "+ ver +" " + obj) for sub in Subject for ver in Verb for obj in Object]
for sentence in All_sentences:
 print(sentence)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [24]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

# Creating a matrix with output columns with input vectors(N)
import numpy as np
x = np.array([2,4,6,9]) 
N = 4
y = np.column_stack([x**(N-1-i) for i in range(N)])
print(y)




[[  8   4   2   1]
 [ 64  16   4   1]
 [216  36   6   1]
 [729  81   9   1]]


In [29]:
# Another matrix with np.vander function in numpy
import numpy as np
x = np.array([2,4,6,9])
N = 4
b = np.vander(x,N,increasing = False)
print(b)



[[  8   4   2   1]
 [ 64  16   4   1]
 [216  36   6   1]
 [729  81   9   1]]


In [27]:
# deterninant of both the matrices
np.linalg.det(y)

1680.0000000000016

In [30]:
np.linalg.det(b)

1680.0000000000016